### PR TITLE
Refactored initialisation code to a generic abstract class

### PR DESCRIPTION
**Pull request by adamrodger**
The previous solution relied on a huge sequence of if statements to check for
each rule whether it was activated or not and configure it if so.

The new solution improves on that by dynamically creating and configuring any
class that implements the common generic class DiagnosticsRule. This means
that new rules will be discovered at runtime and created automatically instead
of having to remember to add the rule to the list in Program.cs.

### CODE REVIEW

**Comment by adamrodger** [comment]
@dbolkensteyn  I've rebased this branch onto the latest from master so it can still be accepted.

**Comment by dbolkensteyn** [comment]
I have one big doubt about this pull request as it currently is: It spreads the XML configuration to every (configurable) rule, whereas the fact that we use XML at some point should probably be a hidden detail.

**Comment by dbolkensteyn** [comment]
Thank you for the suggestion on changing the XML structure to handle "CommentRegularExpression". I will apply this to improve the XML reading logic.

I will keep this pull request open for a while - I am not yet sure if instantiating the analyzers through reflection or if introducing a base class are good idea at this point of time. But it's definitely a good thing to keep those options in mind.

**Comment by adamrodger** [comment]
Yeah sure, that makes sense. Probably best to create a Configuration class
and then have an XML parsing class that produces it.

That way all the XML is hidden in one class and all the individual rules
can have a strongly typed entry in Configuration. That would make future
refactoring easier as well.

I won't have time to do that myself any time soon but that does sound the
way to go.

**Comment by dbolkensteyn** [comment]
I believe that this has now been fixed in the master of the SonarLint for Visual Studio project (which has been extracted out of this repository) - therefore I am closing this PR

**Pull request closed without merging**
